# Generated by Django 2.0.1 on 2018-01-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
                ('courseCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueSize', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=30)),
                ('studentID', models.CharField(max_length=20)),
                ('studentEmail', models.CharField(max_length=50)),
                ('studentPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taID', models.CharField(max_length=20)),
                ('taCode', models.CharField(max_length=20)),
                ('taName', models.CharField(max_length=30)),
                ('currentStudent', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTAs',
            field=models.ManyToManyField(to='home.TA'),
        ),
    ]
