# Generated by Django 2.0.1 on 2018-01-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='ta',
        ),
        migrations.AddField(
            model_name='ta',
            name='currentStudent',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
