# Generated by Django 2.0.1 on 2018-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='currentStudent',
            field=models.CharField(default='', max_length=30),
        ),
    ]
