# Generated by Django 2.0.1 on 2018-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180127_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queueSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ta',
            name='currentStudent',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ta',
            name='taName',
            field=models.CharField(max_length=30),
        ),
    ]
