# Generated by Django 2.0.1 on 2018-01-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180127_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentIssue',
            field=models.CharField(default='', max_length=200),
        ),
    ]
