# Generated by Django 2.0.1 on 2018-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180127_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queueSize',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
