# Generated by Django 2.0.1 on 2018-01-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_studentissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='courseNum',
        ),
    ]
