# Generated by Django 2.0.1 on 2018-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180127_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='queueSize',
        ),
    ]
